package ar.com.protean.horario.genetico.enums;

public enum MateriaEnum {
	NO_DISPONIBLE,
	Biologia,
	C_de_C,
	C_E_C,
	Ciencias_Naturales,
	Ciencias_Sociales,
	Cu_y_Co,
	DDHH,
	Derecho,
	E_C_I__I_P_C,
	E_C_I__Microemp,
	E_C_I__Per_Mu_Co,
	E_C_I__S_I_C,
	E_C_I__S_I_L,
	Economia,
	Educacion_Artistica,
	Filosofia,
	Fisica,
	Fisico_Quimica,
	Geografia,
	Historia,
	Ingles,
	Lengua_y_Lit,
	Matematica,
	Practicas_del_Lenguaje,
	Proy_De_Inv,
	Psicologia,
	Quimica,
	S_I_C,
	Salud_y_Adol,
	Sociologia,
	T_I_C,
	Tecnologia_de_Gest,
	Teoria_de_las_Org
}
